spring.application.name=publicaciones-service
server.port=8082

#Base de datos PostgreSQL
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#RabbitMQ configuration
spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

#Schema de la base de datos(SUPABASE)
spring.jpa.properties.hibernate.default_schema=${DB_SCHEMA}
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1

#Supabase Storage (subida de imagenes)
supabase.url=${SUPABASE_URL}
supabase.service-key=${SUPABASE_SERVICE_KEY}
supabase.storage.bucket=${SUPABASE_BUCKET:publicaciones}
 
#Tamanio maximo de archivos multipart (fotos)
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB